import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'



export default function Home({repositories}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <ul>
    {repositories.map((repo) => (
      <li key={repo} > {repo} </li>
    ))}
   </ul>
    </>
  )
}


export const getServerSideProps: GetServerSideProps = async () => {
  const response = await fetch(`https://api.github.com/users/1pedr1n/repos`)
const data = await response.json();
 
  const repoNames = data.map(item => item.name)
 

     return {
      props: {
        repositories: repoNames
      }
     }
    }