import Head from 'next/head'
import { useEffect, useState } from 'react'



export default function Home() {
  const [repositories, setRepositories] = useState<string[]>([])
  useEffect(() => {
fetch(`https://api.github.com/users/1pedr1n/repos`  ).then(
  response => response.json()
).then(
 ( data )=> {
const repoNames = data.map(item => item.name)
   setRepositories(repoNames)
  }
)
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <ul>
    {repositories.map((repo) => (
      <li key={repo} > {repo} </li>
    ))}
   </ul>
    </>
  )
}
