import { GetServerSideProps, GetStaticProps } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'



export default function Home({repositories, date}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{date} </h1>
   <ul>
    {repositories.map((repo) => (
      <li key={repo} > {repo} </li>
    ))}
   </ul>
    </>
  )
}


export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch(`https://api.github.com/users/1pedr1n/repos`)
const data = await response.json();
 
  const repoNames = data.map(item => item.name)
 

     return {
      props: {
        repositories: repoNames,
        date: new Date().toISOString()
      },
      revalidate:5
      
     }
    }